export const SCHEMA = {
  '0000': {
    desc: 'Abertura do Arquivo',
    cols: [
      'REG',
      'NOME_ESC',
      'COD_VER',
      'CPF',
      'NOME',
      'IND_SIT_INICIO_PER',
      'IND_SIT_ESPECIAL_PER',
      'DT_SIT_ESP',
      'DT_INI',
      'DT_FIN',
    ],
  },
  '0010': { desc: 'Parâmetros de Tributação', cols: ['REG', 'FORMA_APUR'] },
  '0030': {
    desc: 'Dados do Contabilista',
    cols: ['REG', 'IDENT_NOME', 'IDENT_CPF_CNPJ', 'IDENT_CRC', 'END_EMAIL', 'FONE'],
  },
  '0040': {
    desc: 'Imóvel Rural',
    cols: [
      'REG',
      'COD_IMOVEL',
      'PAIS',
      'MOEDA',
      'CAD_ITR',
      'CAEPF',
      'INSCR_ESTADUAL',
      'NOME_IMOVEL',
      'ENDERECO',
      'NUM',
      'COMPL',
      'BAIRRO',
      'UF',
      'COD_MUN',
      'CEP',
      'TIPO_EXPLORACAO',
      'PARTICIPACAO',
    ],
  },
  '0045': {
    desc: 'Cadastro de Terceiros',
    cols: ['REG', 'COD_IMOVEL', 'TIPO_CONTRAPARTE', 'CPF_CNPJ', 'NOME', 'PERCENTUAL'],
  },
  '0050': {
    desc: 'Conta Bancária',
    cols: ['REG', 'COD_CONTA', 'PAIS_CTA', 'BANCO', 'NOME_BANCO', 'AGENCIA', 'NUM_CTA'],
  },
  Q100: {
    desc: 'Demonstrativo do Livro Caixa',
    cols: [
      'REG',
      'DATA',
      'COD_IMOVEL',
      'COD_CONTA',
      'NUM_DOC',
      'TIPO_DOC',
      'HISTORICO',
      'ID_PARTICIPANTE',
      'TIPO_LANC',
      'VL_ENTRADA',
      'VL_SAIDA',
      'SLD_FIN',
    ],
  },
  Q200: { desc: 'Resumo Mensal', cols: ['REG', 'MES', 'VL_ENTRADA', 'VL_SAIDA', 'SLD_FIN'] },
  '9999': { desc: 'Encerramento do Arquivo', cols: ['REG', 'QTD_LINHAS'] },
}
